services:
  localstack:
    image: localstack/localstack:latest
    container_name: enterprise-agentic-rag-localstack
    ports:
      - "4566:4566"
    environment:
      AWS_DEFAULT_REGION: us-east-1
      LOCALSTACK_AUTH_TOKEN: ${LOCALSTACK_AUTH_TOKEN}
    volumes:
      - "./localstack/init:/etc/localstack/init/ready.d"
      - "localstack_data:/var/lib/localstack"

volumes:
  localstack_data: